var playership1 = "./img/spaceship_sprite.png";
var enemyRound = "./img/enemyround.png";
var background1 = "./img/background.png";
var gasPlanetSrc = "./img/gas_planet.png"
var blackHoleSrc = "./img/Black_Hole.png"
var ufoSrc = "./img/ufo.png"
var nebulaSrc = "./img/nebula.png"
var greenUfoSrc = "./img/greenufo.png"
var canvasWidth = 1200;
var canvasHeight = 700;
var mouseX = 0.0;
var mouseY = 0.0;
var base = 10.00;
var enemies = [];
var fixedEnemies = [];
var bulletArr = [];
var objArray = [];
var num = 0;
var numy = 0;
var score = 0;
var hit_delay = 0;
var gameOver = false;
var gameStart = false;
this.game = 0
main = this;